version: "3.7"
services:
  mesh:
    build:
      context: ./
      dockerfile: Dockerfile-all
      # volumes:
      # - ./.meshrc.yaml:/work/.meshrc.yaml
      args:
        tag: latest
        packages: "@graphql-mesh/handler-federation @graphql-mesh/openapi @graphql-mesh/json-schema @graphql-mesh/postgraphile @graphql-mesh/grpc @graphql-mesh/soap @graphql-mesh/mongoose @graphql-mesh/odata @graphql-mesh/thrift @graphql-mesh/tuql @graphql-mesh/mysql @graphql-mesh/neo4j @graphql-mesh/transform-extend @graphql-mesh/transform-federation @graphql-mesh/merger-federation @apollo/gateway apollo-server"
    image: hiroyukiosaki/graphql-mesh:latest-all
    ports:
    - "4000:4000"
  mesh-ver:
    build:
      context: ./
      dockerfile: Dockerfile-all
      # volumes:
      # - ./.meshrc.yaml:/work/.meshrc.yaml
      args:
        tag: v0.1.17
        packages: "@graphql-mesh/handler-federation @graphql-mesh/openapi @graphql-mesh/json-schema @graphql-mesh/postgraphile @graphql-mesh/grpc @graphql-mesh/soap @graphql-mesh/mongoose @graphql-mesh/odata @graphql-mesh/thrift @graphql-mesh/tuql @graphql-mesh/mysql @graphql-mesh/neo4j @graphql-mesh/transform-extend @graphql-mesh/transform-federation @graphql-mesh/merger-federation @apollo/gateway apollo-server"
    image: hiroyukiosaki/graphql-mesh:v0.1.17-all
    ports:
    - "4000:4000"