version: "3.7"
services:
  mesh:
    build:
      context: ./
      dockerfile: Dockerfile
      # volumes:
      # - ./.meshrc.yaml:/work/.meshrc.yaml
    image: hiroyukiosaki/graphql-mesh:v0.1.9
    ports:
    - "4000:4000"