version: "3.7"
services:
  mesh:
    build:
      context: ./
      dockerfile: Dockerfile
      # volumes:
      # - ./.meshrc.yaml:/work/.meshrc.yaml
    image: hiroyukiosaki/graphql-mesh:latest
    ports:
    - "4000:4000"
  mesh-ver:
    build:
      context: ./
      dockerfile: Dockerfile
      # volumes:
      # - ./.meshrc.yaml:/work/.meshrc.yaml
    image: hiroyukiosaki/graphql-mesh:v0.1.15
    ports:
    - "4000:4000"