apiVersion: v1
data:
  case-additional-resolvers.js: |
    const resolvers = {
      Case: {
        population: async ({ countryRegion }, args, { WorldPop }) => {
          if (countryRegion) {
            return await WorldPop.api.population({
              country: countryRegion,
            });
          }
          throw Error(
            "countryRegion is a needed field at case level to get population info"
          );
        },
      },
    };

    module.exports = { resolvers };
  query-additional-resolvers.js: |
    const resolvers = {
      Query: {
        stat: async (root, args, { WorldPop, Covid }) => {
          const worldPop = await WorldPop.api.population({
            country: args.country,
          });
          const covid = await Covid.api.case({
            countryRegion: args.country,
          });
          const numberPop = worldPop.records[0].fields.value;

          const numberConfirmed = covid.confirmed;
          const numberDeath = covid.deaths;
          const numberRecovered = covid.recovered;
          return {
            confirmedRatio: ((numberConfirmed * 1.0) / numberPop) * 1.0,
            deathRatio: ((numberDeath * 1.0) / numberPop) * 1.0,
            recoveredRatio: ((numberRecovered * 1.0) / numberPop) * 1.0,
            case: covid,
            population: worldPop
          };
        },
      },
    };

    module.exports = { resolvers };
  worldPop.json: |-
    {
      "type": "object",
      "title": "Api Population",
      "description": "Desc Api Population",
      "properties": {
          "records": {
              "type": "array",
              "items": {
                  "type": "object",
                  "title": "Result",
                  "description": "Result of API",
                  "properties": {
                      "fields": {
                          "type": "object",
                          "properties": {
                              "country_name": {
                                  "type": "string"
                              },
                              "value": {
                                  "type": "number"
                              },
                              "year": {
                                  "type": "string"
                              }
                          }
                      }
                  }
              }
          }
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: src-cm
