apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mesh
  name: mesh
spec:
  containers:
  - image: hiroyukiosaki/graphql-mesh:v0.1.9-all
    name: mesh
    resources: {}
    ports:
    - containerPort: 4000
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
